import { GalleryItem } from "@/lib/types";
// import harmonicBloom from '@/public/gallery/Cyclomat-Project-172-20260427-102545.jpeg'

export const galleryIntro = {
  heading: "Gallery",
  subtext:
    "A collection of artwork created with Cyclomat. Each piece is generated purely through harmonic motion and expressive styles.",
};

export const galleryItems: GalleryItem[] = [
  {
    id: "shape-harmony",
    title: "Shape Harmony",
    description: "Three shapes together, sharing harmonic relationships and colors.",
    arms: 3,
    layers: 3,
    complexity: "simple",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Project-223-20260430-154506.jpeg",
  },
  {
    id: "seusse-spiral",
    title: "Seusse Spiral",
    description: "Varying line width, color, and geometry produces a funhouse effect.",
    arms: 3,
    layers: 1,
    complexity: "moderate",
    colors: ["#c084fc"],
    source: "/gallery/Cyclomat-Sample-Seuss-20260427-095312.jpeg",
  },
  {
    id: "jelly-heads",
    title: "Jelly Heads",
    description: "Smooth color and geometric interpolation between four-petal shapes.",
    arms: 2,
    layers: 1,
    complexity: "moderate",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Sample-Crossroads-20260427-101223.jpeg",
  },
  {
    id: "auric-telemetry",
    title: "Auric Telemetry",
    description: "Harmonically related shapes and varying styles evoke energy rays and fields rippling outward.",
    arms: 4,
    layers: 4,
    complexity: "complex",
    colors: ["#67e8f9", "#a5b4fc"],
    source: "/gallery/Cyclomat-Project-215-20260427-072747.jpeg",
  },
  {
    id: "windswept",
    title: "Windswept",
    description: "A dense form is progressively phase shifted. tinted and blurred.",
    arms: 3,
    layers: 1,
    complexity: "simple",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Windswept-Dark-20260427-103401.jpeg",
  },
  {
    id: "resonance-field",
    title: "Resonance Field",
    description: "Multiple layers with parameter offsets create a shimmering interference pattern.",
    arms: 3,
    layers: 4,
    complexity: "moderate",
    colors: ["#818cf8", "#e879f9", "#fb7185"],
    source: "/gallery/Cyclomat-Project-17-20260429-115102.jpeg",
  },
  {
    id: "harmonic-bloom",
    title: "Harmonic Bloom",
    description: "A flowering form created by layering two shapes with complementary frequencies.",
    arms: 2,
    layers: 2,
    complexity: "complex",
    colors: ["#a78bfa", "#f472b6"],
    source: "/gallery/Cyclomat-Project-172-20260427-102545.jpeg",
  },
  {
    id: "twin-orbit",
    title: "Twin Orbit",
    description: "Two keyframed shapes positioned opposing, with contrasting colors and partial opacity.",
    arms: 3,
    layers: 2,
    complexity: "moderate",
    colors: ["#4ade80", "#22d3ee"],
    source: "/gallery/Cyclomat-Project-211-20260427-125800.jpeg",
  },
  {
    id: "crystal-challice",
    title: "Crystal Chalice",
    description: "Simple rotations extruded vertically to evoke a delicate, colorful structure.",
    arms: 2,
    layers: 1,
    complexity: "moderate",
    colors: ["#67e8f9", "#a5b4fc"],
    source: "/gallery/Cyclomat-Sample-Chalice-20260427-102211.jpeg",
  },
  {
    id: "distressed-blend",
    title: "Distressed Blend",
    description: "Using blend modes and layout to produce distressed interference effects.",
    arms: 2,
    layers: 3,
    complexity: "moderate",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Project-180-20260429-113729.jpeg",
  },
  {
    id: "tint-weaves",
    title: "Tinted Weaves",
    description: "Three arms in counter-rotation produce a dense, woven lattice of curves, tinted and rotated.",
    arms: 3,
    layers: 1,
    complexity: "simple",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Sample-Tints-20260427-095012.jpeg",
  },
  {
    id: "mayan-sunrise",
    title: "Mayan Sunrise",
    description: "Correlation and interference between shapes and layers give rise to new tonal structures.",
    arms: 3,
    layers: 3,
    complexity: "complex",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Project-129-20260429-131336.jpeg",
  },
  {
    id: "plumage",
    title: "Plumage",
    description: "Velvet neo-arcade colors and echoing feahers to attract any mate.",
    arms: 3,
    layers: 3,
    complexity: "moderate",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Project-223-20260503-214505.jpeg",
  },
  {
    id: "drafting-table",
    title: "Drafting Table",
    description: "An homage to the vast array of hand-crafted drawing machines created through the ages.",
    arms: 3,
    layers: 4,
    complexity: "complex",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Project-48-20260503-215850.jpeg",
  },
  {
    id: "disco",
    title: "Disco Chandalier",
    description: "Staring upward at a white ball of healing light. That's right.",
    arms: 3,
    layers: 6,
    complexity: "complex",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Project-161-20260503-215025.jpeg",
  },
  {
    id: "offset-print",
    title: "Offset Print",
    description: "With a nod to those in the mechanical plotting and drawing realms, who constantly inspire us to go further. Or farther, maybe.",
    arms: 3,
    layers: 5,
    complexity: "moderate",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Project-200-20260508-204018.jpeg",
  },    
  {
    id: "hue-manity",
    title: "Huemanity",
    description: "Most of the hues known to computer science, layered with pride above the bright glow our human joy to create.",
    arms: 3,
    layers: 1,
    complexity: "moderate",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Project-176A-20260508-203702.jpeg",
  },    
  {
    id: "starry-nite",
    title: "Starry Nite",
    description: "Some shapes mildly evocative of those found within respected artforms.",
    arms: 3,
    layers: 6,
    complexity: "moderate",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Project-220-20260508-204825.jpeg",
  },    

  // {
  //   id: "bio-optics",
  //   title: "Bio Optics",
  //   description: "A symphony of outward-looping hypocycloids and inward-looping epicycloids.",
  //   arms: 3,
  //   layers: 3,
  //   complexity: "complex",
  //   colors: ["#60a5fa", "#34d399"],
  //   source: "/gallery/Cyclomat-Project-222-20260503-213258.jpeg",
  // },
];
