import { GalleryItem } from "@/lib/types";
// import harmonicBloom from '@/public/gallery/Cyclomat-Project-172-20260427-102545.jpeg'

export const galleryIntro = {
  heading: "Gallery",
  subtext:
    "A collection of artwork created with Cyclomat. Each piece is generated purely through harmonic motion and expressive styles.",
};

export const galleryItems: GalleryItem[] = [
  {
    id: "shape-harmony",
    title: "Shape Harmony",
    description: "Three shapes together, sharing harmonic relationships and colors.",
    arms: 3,
    layers: 3,
    complexity: "simple",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Project-223-20260430-154506.jpeg",
  },
  {
    id: "seusse-spiral",
    title: "Seusse Spiral",
    description: "Varying line width, color, and geometry produces a funhouse effect.",
    arms: 3,
    layers: 1,
    complexity: "moderate",
    colors: ["#c084fc"],
    source: "/gallery/Cyclomat-Sample-Seuss-20260427-095312.jpeg",
  },
  {
    id: "jelly-heads",
    title: "Jelly Heads",
    description: "Smooth color and geometric interpolation between four-petal shapes.",
    arms: 2,
    layers: 1,
    complexity: "moderate",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Sample-Crossroads-20260427-101223.jpeg",
  },
  {
    id: "auric-telemetry",
    title: "Auric Telemetry",
    description: "Harmonically related shapes and varying styles evoke energy rays and fields rippling outward.",
    arms: 4,
    layers: 4,
    complexity: "complex",
    colors: ["#67e8f9", "#a5b4fc"],
    source: "/gallery/Cyclomat-Project-215-20260427-072747.jpeg",
  },
  {
    id: "windswept",
    title: "Windswept",
    description: "A dense form is progressively phase shifted. tinted and blurred.",
    arms: 3,
    layers: 1,
    complexity: "moderate",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Windswept-Dark-20260427-103401.jpeg",
  },
  {
    id: "resonance-field",
    title: "Resonance Field",
    description: "Multiple layers with parameter offsets create a shimmering interference pattern.",
    arms: 3,
    layers: 4,
    complexity: "complex",
    colors: ["#818cf8", "#e879f9", "#fb7185"],
    source: "/gallery/Cyclomat-Project-17-20260429-115102.jpeg",
  },
  {
    id: "harmonic-bloom",
    title: "Harmonic Bloom",
    description: "A flowering form created by layering two shapes with complementary frequencies.",
    arms: 2,
    layers: 2,
    complexity: "complex",
    colors: ["#a78bfa", "#f472b6"],
    source: "/gallery/Cyclomat-Project-172-20260427-102545.jpeg",
  },
  {
    id: "twin-orbit",
    title: "Twin Orbit",
    description: "Two keyframed shapes positioned opposing, with contrasting colors and partial opacity.",
    arms: 3,
    layers: 2,
    complexity: "moderate",
    colors: ["#4ade80", "#22d3ee"],
    source: "/gallery/Cyclomat-Project-211-20260427-125800.jpeg",
  },
  {
    id: "crystal-challice",
    title: "Crystal Chalice",
    description: "Simple rotations extruded vertically to evoke a delicate, colorful structure.",
    arms: 2,
    layers: 1,
    complexity: "simple",
    colors: ["#67e8f9", "#a5b4fc"],
    source: "/gallery/Cyclomat-Sample-Chalice-20260427-102211.jpeg",
  },
  {
    id: "distressed-blend",
    title: "Distressed Blend",
    description: "Using blend modes and layout to produce distressed interference effects.",
    arms: 2,
    layers: 1,
    complexity: "moderate",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Project-180-20260429-113729.jpeg",
  },
  {
    id: "tint-weaves",
    title: "Tinted Weaves",
    description: "Three arms in counter-rotation produce a dense, woven lattice of curves, tinted and rotated.",
    arms: 3,
    layers: 1,
    complexity: "moderate",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Sample-Tints-20260427-095012.jpeg",
  },
  {
    id: "mayan-sunrise",
    title: "Mayan Sunrise",
    description: "Construction and interference between shapes, and betwen layers, gives rise to new tonal structures.",
    arms: 3,
    layers: 3,
    complexity: "complex",
    colors: ["#60a5fa", "#34d399"],
    source: "/gallery/Cyclomat-Project-129-20260429-131336.jpeg",
  },
  
  // {
  //   id: "phase-mandala",
  //   title: "Phase Mandala",
  //   description: "A mandala-like composition created by phase-shifting a single shape across multiple layers.",
  //   arms: 2,
  //   layers: 5,
  //   complexity: "complex",
  //   colors: ["#fbbf24", "#f97316", "#ef4444"],
  //   source: "/gallery/____.jpeg",
  // },
  
  // {
  //   id: "fractal-echo",
  //   title: "Fractal Echo",
  //   description: "Four arms create self-similar patterns that echo at different scales.",
  //   arms: 4,
  //   layers: 3,
  //   complexity: "complex",
  //   colors: ["#f472b6", "#a78bfa", "#60a5fa"],
  //   source: "/gallery/____.jpeg",
  // },
  // {
  //   id: "solar-corona",
  //   title: "Solar Corona",
  //   description: "Warm-toned layers radiating outward, inspired by the geometry of light.",
  //   arms: 3,
  //   layers: 3,
  //   complexity: "moderate",
  //   colors: ["#fbbf24", "#f97316", "#dc2626"],
  //   source: "/gallery/____.jpeg",
  // },
];
